name: check-mixed-line-endings
author: erclu
description: "Checks for non-binary files with mixed line endings (CRLF and LF) in given path"

branding:
  icon: file-text
  color: gray-dark

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.exclude }}

inputs:
  path:
    description: Path to check
    required: false
    default: "."
  exclude:
    description: Space-separated list of dirs to exclude
    required: false
    default: ""
